namespace OllamaFlow.Core.Models.OpenAI
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text.Json;
    using System.Text.Json.Serialization;

    /// <summary>
    /// OpenAI chat completion choice.
    /// </summary>
    public class OpenAIChatChoice
    {
        /// <summary>
        /// Index of this choice.
        /// </summary>
        [JsonPropertyName("index")]
        public int Index { get; set; }

        /// <summary>
        /// Chat message generated by the model.
        /// </summary>
        [JsonPropertyName("message")]
        public OpenAIChatMessage Message { get; set; }

        /// <summary>
        /// Delta message for streaming responses.
        /// </summary>
        [JsonPropertyName("delta")]
        public OpenAIChatMessage Delta { get; set; }

        /// <summary>
        /// Log probabilities information.
        /// </summary>
        [JsonPropertyName("logprobs")]
        public OpenAIChatLogprobs Logprobs { get; set; }

        /// <summary>
        /// Reason the generation stopped.
        /// Possible values: "stop", "length", "tool_calls", "content_filter", "function_call"
        /// </summary>
        [JsonPropertyName("finish_reason")]
        public string FinishReason { get; set; }

        /// <summary>
        /// OpenAI chat choice.
        /// </summary>
        public OpenAIChatChoice()
        {
        }
    }
}