namespace OllamaFlow.Core.Models.Ollama
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;

    /// <summary>
    /// Ollama streaming chat completion result.
    /// Used for intermediate streaming responses.
    /// </summary>
    public class OllamaStreamingChatCompletionResult
    {
        /// <summary>
        /// The model that generated the response.
        /// </summary>
        [JsonPropertyName("model")]
        public string Model { get; set; }

        /// <summary>
        /// The timestamp of when the response was created.
        /// </summary>
        [JsonPropertyName("created_at")]
        public DateTime? CreatedAt { get; set; }

        /// <summary>
        /// The partial message generated by the model.
        /// </summary>
        [JsonPropertyName("message")]
        public OllamaChatMessage Message { get; set; }

        /// <summary>
        /// Whether this is the final chunk in the stream.
        /// </summary>
        [JsonPropertyName("done")]
        public bool Done { get; set; }

        /// <summary>
        /// Ollama streaming chat completion result.
        /// </summary>
        public OllamaStreamingChatCompletionResult()
        {
        }
    }
}